#!/usr/bin/env python

from netmiko import ConnectHandler
from getpass import getpass

password = getpass()

cisco4 ={
 'device_type': 'cisco_ios',
 'host': 'cisco4.lasthop.io',
 'username': 'pyclass',
 'password': password,
 'secret': password,
 'session_log': 'my_output.txt'
}

with ConnectHandler(**cisco4) as con:
    con.config_mode()
    con.write_channel('disable\n')
    time.sleep(2)
    output= con.read_channel()
    print(output)
    
        
